services:
  # webui:
  #   image: ghcr.io/open-webui/open-webui:git-09a81eb
  #   expose:
  #     - 8080/tcp
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434
  #   volumes:
  #     - ./open-webui:/app/backend/data
  #   depends_on:
  #     - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    devices:
      - "/dev/dri/card1:/dev/dri/card1"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    # devices:
    #   - /dev/dri
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped

  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - 8010:8000
    restart: unless-stopped
