services:
  webui:
    image: ghcr.io/open-webui/open-webui:git-09a81eb
    expose:
      - 8080/tcp
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    devices:
      - /dev/dri
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped
